### ISSUE TITLE
Overworld Portal Restrictions

### ISSUE THREAD

**Issue by Mohron** [Terrails/NetherUtils#4]
NetherUtils-1.12-1.2.11 via Forever Stranded Lost Souls 1.0.3.7-B3

![image](https://user-images.githubusercontent.com/3623122/36080262-13e6b626-0f53-11e8-94e8-a8956e696451.png)

The overworld portal is currently restricted to the Vanilla Nether (DIM-1) instead of any world with the Nether Dimension Type (or potentially, any non-overworld world type).  Would it be possible to change this restriction to the Nether Dimension Type instead so that we can use the portal on our server that has duplicate nethers for multiple teams to play through the pack with their own starting dim.

https://github.com/Terrails/NetherUtils/blob/d90515a04c30e68baf8b3092685d2d0856fa3e12/src/main/java/terrails/netherutils/blocks/portal/nether/BlockPortal.java#L63
https://github.com/Terrails/NetherUtils/blob/d90515a04c30e68baf8b3092685d2d0856fa3e12/src/main/java/terrails/netherutils/gui/client/portal/nether/GuiPortal.java#L129

Thank you for your consideration!

**Comment by Mohron** [comment]
So finally got the chance to test this... somehow, the nether portal teleported us from our duplicate nether to, _drumroll_, the vanilla nether.

**Comment by Terrails** [comment]
woah thats weird, gonna look into it

**Comment by Terrails** [comment]
I'm not sure if this will work but can you please test it as soon as you can.
https://www.dropbox.com/s/zl499ey6tilc8tq/NetherUtils-1.12-1.3.17.jar?dl=0

**Comment by Mohron** [comment]
The change in mod version meant I had to test it in SSP. I get this when standing on the portal now (in the vanilla nether):
![image](https://user-images.githubusercontent.com/3623122/36562004-2cc57958-17db-11e8-8642-078d9b3f63f2.png)

**Comment by Mohron** [comment]
Something seems to be canceling all the cross world teleport events. Can't even leave the nether using commands.

**Comment by Terrails** [comment]
yeah its the portal item, you need to get a beacon by default

**Comment by Mohron** [comment]
I crafted a beacon, same error message. Also this is still hardcoded to dim-1 
https://github.com/Terrails/NetherUtils/blob/1.12.x/src/main/java/terrails/netherutils/event/EntityEvent.java#L109

**Comment by Terrails** [comment]
yeah realized that need to fix it

**Comment by Terrails** [comment]
Did you get an achievement when you crafted the beacon?

**Comment by Mohron** [comment]
I did.
![image](https://user-images.githubusercontent.com/3623122/36563573-2bb48126-17e0-11e8-8c68-08b5876e0eb4.png)

**Comment by Terrails** [comment]
Just for testing can you remove the item to leave string (minecraft:beacon) in the config (nether category) and test the portal

**Comment by Mohron** [comment]
That was it... Any chance you can make sure that event handler doesn't cancel non-portal triggered event like commands?

And after removing that setting both the vanilla and copy nether take me to the overworld.

**Comment by Terrails** [comment]
Alright, does it take you back to the same dimension too? Since I just want to be sure. I'll just polish everything and fix that event now.

**Comment by Mohron** [comment]
Yes, takes me back to the nether portal I used last, awesome!

**Comment by Terrails** [comment]
I really can't make it work if its a command. The only thing I could do is disable the usage of the portal from netherutils and vanilla portal which would probably leave a lot of other items that teleport around enabled. I could maybe make it so a certain list of commands in the config allows that since there is a command event in which I could store the last command a player used and use it in the change dimension event.

**Comment by Mohron** [comment]
I just mean don't block commands with your listener. That required item thing blocked me teleporting to another dimension even when using an admin command.

**Comment by Terrails** [comment]
I don't think I cant do it without blocking commands cause the event doesn't provide something like that, but like I said the only thing would probably be just storing the last used command into a capability and then using it in the entity travel to dimension event to check

**Comment by Mohron** [comment]
Fair enough, I forget sometimes how little information is available with forge events

**Comment by Terrails** [comment]
Now when I think about it, storing the last command and the world time it was used at would create more problems since I need to get the parameters which are used in the command, check if they're players... etc... I don't think I'll do this. I'll better just check if the player is OP and allow it only then.

**Comment by Mohron** [comment]
That would probably be the most appropriate forge way of doing it!
