### ISSUE TITLE
Portal Slave disappears in overworld

### ISSUE THREAD

**Issue by jbouchet** [Terrails/NetherUtils#5]
Hi,
I got a issue with the Portal in the Overworld, when I cross the portal Nether -> Overworld, the portal slave disappear .... 
I recorded a video showing the worries : [link](https://youtu.be/47ngGzOxPjk)
I play with the modpack Forever Stranded Lost Souls.

Some idea ?

**Comment by Terrails** [comment]
Breaking and placing the portal should fix it, also I suggest you to update to the latest version of NetherUtils, I fixed that slow teleportation. Its only 10 seconds now.

**Comment by jbouchet** [comment]
I just saw isn't the last version on modpack ! I try it ;) 
Thanks.
